# -*- coding: utf-8 -*-
"""FJ_update.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VAU3OXXdmBmLM54MdyaNaISheAl912Et

# TCGA-LUSC CT Scan Analysis with TotalSegmentator

This notebook demonstrates how to:
1. Load DICOM files from TCGA dataset
2. Build 3D volumes from CT scans
3. Visualize CT data
4. Perform automatic lung tumor segmentation using TotalSegmentator

## Step 1: Mount Google Drive and Find DICOM Files
"""

from google.colab import drive
drive.mount('/content/drive')

import os

# Path to your TCGA dataset
DATASET_PATH = "/content/drive/MyDrive/nd/manifest-27oBhciT6753657225075401932/TCGA-LUSC"

def find_dicom_files(root):
    """Recursively find all DICOM files in directory"""
    dicom_paths = []
    for dirpath, _, filenames in os.walk(root):
        for f in filenames:
            if f.lower().endswith(".dcm"):
                dicom_paths.append(os.path.join(dirpath, f))
    return dicom_paths

dicoms = find_dicom_files(DATASET_PATH)
print(f"Number of DICOM files found: {len(dicoms)}")
if dicoms:
    print(f"Example DICOM: {dicoms[0]}")

"""## Step 2: Install Required Packages

**IMPORTANT**: After running this cell, you MUST restart the runtime!
Go to: Runtime → Restart runtime
"""

# Install required packages
!pip install -q pydicom numpy matplotlib ipywidgets SimpleITK
!pip install -q git+https://github.com/wasserth/TotalSegmentator.git

print("\n" + "="*60)
print("INSTALLATION COMPLETE!")
print("="*60)
print("⚠️  IMPORTANT: You MUST restart the runtime now!")
print("   Go to: Runtime → Restart runtime")
print("   Then skip this cell and continue from Step 3")
print("="*60)

"""## Step 3: Load DICOM Series and Build 3D Volume

**Run this cell AFTER restarting the runtime**
"""

import pydicom
import numpy as np
import os

def load_dicom_series(folder):
    """
    Load DICOM series from folder and build 3D volume
    Returns: volume (3D numpy array), spacing (z,y,x), slices list
    """
    # Read all DICOM slices
    slices = []
    for f in sorted(os.listdir(folder)):
        if f.lower().endswith(".dcm"):
            path = os.path.join(folder, f)
            try:
                ds = pydicom.dcmread(path)
                if hasattr(ds, 'PixelData'):
                    slices.append(ds)
            except Exception as e:
                print(f"Warning: Could not read {f}: {e}")
                continue

    if len(slices) == 0:
        raise ValueError(f"No valid DICOM slices found in folder: {folder}")

    # Sort by slice location (Z position)
    slices.sort(key=lambda x: float(x.ImagePositionPatient[2]))

    # Build 3D numpy volume
    volume = np.stack([s.pixel_array for s in slices]).astype(np.int16)

    # Convert to Hounsfield Units
    for i, s in enumerate(slices):
        intercept = float(s.RescaleIntercept)
        slope = float(s.RescaleSlope)
        volume[i] = volume[i] * slope + intercept

    # Extract spacing information
    px_spacing = list(map(float, slices[0].PixelSpacing))  # [row_spacing, col_spacing]

    # Calculate slice spacing
    try:
        z_spacing = abs(
            float(slices[1].ImagePositionPatient[2]) -
            float(slices[0].ImagePositionPatient[2])
        )
    except:
        z_spacing = float(slices[0].SliceThickness)

    spacing = (z_spacing, px_spacing[0], px_spacing[1])  # (z, y, x)

    return volume, spacing, slices

# Example: Load one patient's CT scan
patient_folder = "/content/drive/MyDrive/nd/manifest-27oBhciT6753657225075401932/TCGA-LUSC/TCGA-34-2605/08-10-1989-NA-CT CHEST-64467/2.000000-Helical 5s-02217"

print("Loading DICOM series...")
volume, spacing, dicom_slices = load_dicom_series(patient_folder)

print(f"Volume shape: {volume.shape}")
print(f"Number of slices: {len(dicom_slices)}")
print(f"Spacing (z, y, x): {spacing}")
print(f"HU range: [{volume.min()}, {volume.max()}]")

"""## Step 4: Visualize CT Scans"""

import matplotlib.pyplot as plt
import numpy as np

def window_image(img, window_center=-600, window_width=1500):
    """Apply windowing for better visualization"""
    img_min = window_center - window_width // 2
    img_max = window_center + window_width // 2
    img = np.clip(img, img_min, img_max)
    return img

def show_slice(volume, slice_index=None, window=True):
    """Display a single slice"""
    if slice_index is None:
        slice_index = volume.shape[0] // 2  # middle slice

    img = volume[slice_index]
    if window:
        img = window_image(img)

    plt.figure(figsize=(6, 6))
    plt.imshow(img, cmap="gray")
    plt.title(f"Slice {slice_index} (Lung Window)")
    plt.axis("off")
    plt.show()

# Show middle slice
show_slice(volume)

# Interactive slice viewer
from ipywidgets import interact, IntSlider

def scroll_slices(index):
    plt.figure(figsize=(6, 6))
    plt.imshow(window_image(volume[index]), cmap="gray")
    plt.title(f"Slice {index}/{volume.shape[0]-1}")
    plt.axis("off")
    plt.show()

interact(scroll_slices,
         index=IntSlider(min=0, max=volume.shape[0]-1, step=1, value=volume.shape[0]//2))

# Maximum Intensity Projection (MIP)
mip = np.max(volume, axis=0)

plt.figure(figsize=(6, 6))
plt.imshow(mip, cmap="gray")
plt.title("Maximum Intensity Projection (MIP)")
plt.axis("off")
plt.show()

"""## Step 5: Save Volume as NIfTI for TotalSegmentator"""

import SimpleITK as sitk

# Convert numpy array to SimpleITK image
sitk_img = sitk.GetImageFromArray(volume)

# IMPORTANT: Apply real DICOM spacing
sitk_img.SetSpacing(spacing[::-1])  # SimpleITK uses (x,y,z) order

# Save as NIfTI
output_path = "/content/ct_volume.nii.gz"
sitk.WriteImage(sitk_img, output_path)

print(f"✓ Saved NIfTI file: {output_path}")
print(f"  Image size: {sitk_img.GetSize()}")
print(f"  Spacing: {sitk_img.GetSpacing()}")

"""## Step 6: Run TotalSegmentator for Lung Tumor Detection"""

# Run TotalSegmentator
print("Running TotalSegmentator...")
print("This may take several minutes...\n")

!TotalSegmentator -i /content/ct_volume.nii.gz -o /content/ts_output --fast

print("\n✓ Segmentation complete!")

"""## Step 7: Load and Visualize Tumor Segmentation"""

# Check what organs were segmented
import os

output_dir = "/content/ts_output"
if os.path.exists(output_dir):
    segmented_organs = [f.replace('.nii.gz', '') for f in os.listdir(output_dir)
                       if f.endswith('.nii.gz')]
    print("Segmented structures:")
    for organ in sorted(segmented_organs):
        print(f"  - {organ}")
else:
    print("Output directory not found!")

# Load tumor mask if available
mask_path = "/content/ts_output/lung_tumor.nii.gz"

if os.path.exists(mask_path):
    mask_img = sitk.ReadImage(mask_path)
    mask = sitk.GetArrayFromImage(mask_img)
    print(f"Tumor mask shape: {mask.shape}")
    print(f"Tumor voxels detected: {np.sum(mask > 0)}")
else:
    print("⚠️  Warning: lung_tumor.nii.gz not found!")
    print("   TotalSegmentator may not have detected tumors in this scan.")
    print("   This is normal for healthy scans or early-stage disease.")

    # Try loading lungs instead
    lung_paths = ['/content/ts_output/lung_upper_lobe_left.nii.gz',
                  '/content/ts_output/lung_upper_lobe_right.nii.gz']

    for lp in lung_paths:
        if os.path.exists(lp):
            mask_img = sitk.ReadImage(lp)
            mask = sitk.GetArrayFromImage(mask_img)
            print(f"\nLoaded {os.path.basename(lp)} instead")
            break

# Visualize segmentation overlay
def show_overlay(volume, mask, slice_index=None, alpha=0.5):
    """Show CT scan with segmentation overlay"""
    if slice_index is None:
        slice_index = volume.shape[0] // 2

    plt.figure(figsize=(8, 8))

    # Show CT scan
    plt.imshow(window_image(volume[slice_index]), cmap="gray")

    # Overlay segmentation if present
    if np.any(mask[slice_index] > 0):
        plt.imshow(mask[slice_index], cmap="Reds", alpha=alpha)
        plt.title(f"Slice {slice_index} - Segmentation Overlay")
    else:
        plt.title(f"Slice {slice_index} - No segmentation on this slice")

    plt.axis("off")
    plt.colorbar(label="Segmentation")
    plt.show()

# Find slice with maximum segmentation
if 'mask' in locals():
    slice_sums = np.sum(mask, axis=(1, 2))
    best_slice = np.argmax(slice_sums)
    print(f"Slice with most segmentation: {best_slice}\n")
    show_overlay(volume, mask, best_slice)

# Interactive overlay viewer
if 'mask' in locals():
    def scroll_overlay(index, alpha=0.5):
        show_overlay(volume, mask, index, alpha)

    from ipywidgets import interact, IntSlider, FloatSlider

    interact(scroll_overlay,
             index=IntSlider(min=0, max=volume.shape[0]-1, value=best_slice, description='Slice'),
             alpha=FloatSlider(min=0, max=1, step=0.1, value=0.5, description='Opacity'))

"""## Summary

This notebook demonstrated:
1. ✓ Loading DICOM files from TCGA-LUSC dataset
2. ✓ Building 3D volumes with proper spacing
3. ✓ Visualizing CT scans with windowing
4. ✓ Running TotalSegmentator for automatic segmentation
5. ✓ Visualizing segmentation results

**Note**: TotalSegmentator may not detect tumors in all scans, especially:
- Healthy/normal scans
- Very early-stage disease
- Scans with imaging artifacts

This is expected behavior and not an error!
"""